<a href="https://colab.research.google.com/github/thcen-dev/ai-health-data-project/blob/midHeap/Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 01

First we are going to upload the dmerc csv file as type "df" and will then display all the names of the rows within the csv.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Replace 'your_file_path.csv' with the actual path to your CSV file
df = pd.read_csv('/content/synthetic_dmerc_base (1).csv')

To get a general feel for what the nature of the data is, we will first look at the first five rows of the data set using "df.head()" and will also look at the bottom five, or "df.tail" of the dataset to ensure accuracy in what we are understanding. We are already given the name of the csv which contains"dmerc", which stands for Durable Medical Equipment, but it is safe practice to ensure data accuracy.

In [ ]:
#pulls the first five rows of the dataset
df.head()

,DSYSRTKY,CLAIMNO,THRU_DT,RIC_CD,CLM_TYPE,DISP_CD,CARR_NUM,PMTDNLCD,PMT_AMT,PRPAYAMT,ASGMNTCD,PROV_PMT,BENE_PMT,SBMTCHRG,ALOWCHRG,DEDAPPLY,HCPCS_YR,PRNCPAL_DGNS_CD,PRNCPAL_DGNS_VRSN_CD,RFR_UPIN,RFR_NPI,DOB_DT,RACE_CD,CNTY_CD,STATE_CD,CWF_BENE_MDCR_STUS_CD,CLM_BENE_PD_AMT,ACO_ID_NUM,ICD_DGNS_CD1,ICD_DGNS_VRSN_CD1,ICD_DGNS_CD2,ICD_DGNS_VRSN_CD2,ICD_DGNS_CD3,ICD_DGNS_VRSN_CD3,ICD_DGNS_CD4,ICD_DGNS_VRSN_CD4,ICD_DGNS_CD5,ICD_DGNS_VRSN_CD5,ICD_DGNS_CD6,ICD_DGNS_VRSN_CD6,ICD_DGNS_CD7,ICD_DGNS_VRSN_CD7,ICD_DGNS_CD8,ICD_DGNS_VRSN_CD8,ICD_DGNS_CD9,ICD_DGNS_VRSN_CD9,ICD_DGNS_CD10,ICD_DGNS_VRSN_CD10,ICD_DGNS_CD11,ICD_DGNS_VRSN_CD11,ICD_DGNS_CD12,ICD_DGNS_VRSN_CD12
0,750,370940371571,20220224,M,72,1,80929,2,2222,222.20,N,2222,0,3932.61,2925,222.20,0,G87.1,0,NaN,7483169078,5,4,451,28,10,0,NaN,A62.1,0.00,NaN,NaN,I14.2,0.00,NaN,NaN,P84.0,0.00,B50.8,0.00,D42.7,0.00,G65.1,0.00,K53.3,0.00,NaN,NaN,J81.3,0.00,D14.0,0.00
1,222,591576890071,20240618,M,72,1,18414,3,1314,131.40,N,1314,0,2621.24,2147,131.40,0,A80.5,0,NaN,2625961895,6,3,970,70,10,0,NaN,A80.9,0.00,NaN,NaN,G77.3,0.00,NaN,NaN,NaN,NaN,C28.7,0.00,A92.6,0.00,E45.1,0.00,NaN,NaN,A62.7,0.00,NaN,NaN,C75.8,0.00
2,178,477751738951,20230527,M,72,1,25702,4,848,84.80,N,848,0,1471.46,1248,84.80,0,L22.5,0,NaN,7412281974,3,4,312,38,10,0,NaN,NaN,NaN,NaN,NaN,B35.6,0.00,C81.5,0.00,A46.2,0.00,NaN,NaN,K26.4,0.00,H53.4,0.00,F54.3,0.00,I86.5,0.00,NaN,NaN,P70.8,0.00
3,779,392843769636,20230204,M,72,1,55375,14,1365,136.50,N,1365,0,2178.37,1858,136.50,0,D76.0,0,NaN,4476855727,2,0,18,1,10,0,NaN,C57.2,0.00,G49.6,0.00,NaN,NaN,N37.0,0.00,NaN,NaN,E11.5,0.00,E71.3,0.00,L81.0,0.00,NaN,NaN,N62.8,0.00,NaN,NaN,NaN,NaN
4,160,518369036545,20241123,M,72,1,83124,B,2124,212.40,A,2124,0,3760.37,3212,212.40,0,N64.7,0,NaN,3708693,5,3,154,53,10,0,NaN,NaN,NaN,E66.3,0.00,J57.2,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A27.9,0.00,B76.9,0.00,NaN,NaN,NaN,NaN

In [ ]:
#pulls the last five rows of the dataset
df.tail()

,DSYSRTKY,CLAIMNO,THRU_DT,RIC_CD,CLM_TYPE,DISP_CD,CARR_NUM,PMTDNLCD,PMT_AMT,PRPAYAMT,ASGMNTCD,PROV_PMT,BENE_PMT,SBMTCHRG,ALOWCHRG,DEDAPPLY,HCPCS_YR,PRNCPAL_DGNS_CD,PRNCPAL_DGNS_VRSN_CD,RFR_UPIN,RFR_NPI,DOB_DT,RACE_CD,CNTY_CD,STATE_CD,CWF_BENE_MDCR_STUS_CD,CLM_BENE_PD_AMT,ACO_ID_NUM,ICD_DGNS_CD1,ICD_DGNS_VRSN_CD1,ICD_DGNS_CD2,ICD_DGNS_VRSN_CD2,ICD_DGNS_CD3,ICD_DGNS_VRSN_CD3,ICD_DGNS_CD4,ICD_DGNS_VRSN_CD4,ICD_DGNS_CD5,ICD_DGNS_VRSN_CD5,ICD_DGNS_CD6,ICD_DGNS_VRSN_CD6,ICD_DGNS_CD7,ICD_DGNS_VRSN_CD7,ICD_DGNS_CD8,ICD_DGNS_VRSN_CD8,ICD_DGNS_CD9,ICD_DGNS_VRSN_CD9,ICD_DGNS_CD10,ICD_DGNS_VRSN_CD10,ICD_DGNS_CD11,ICD_DGNS_VRSN_CD11,ICD_DGNS_CD12,ICD_DGNS_VRSN_CD12
834,753,74252124558,20221005,M,72,1,71337,0,1389,138.90,N,1389,0,2484.59,1795,138.90,0,M66.6,0,NaN,8411378728,5,2,522,97,10,0,NaN,N55.5,0.00,P32.8,0.00,I41.2,0.00,NaN,NaN,NaN,NaN,NaN,NaN,J85.5,0.00,K29.5,0.00,NaN,NaN,N54.0,0.00,NaN,NaN,NaN,NaN
835,130,598863377128,20231205,M,72,1,17240,2,945,94.50,A,945,0,2131.61,1514,94.50,0,H13.8,0,NaN,9063823528,4,3,477,84,10,0,NaN,NaN,NaN,NaN,NaN,K47.3,0.00,NaN,NaN,NaN,NaN,M99.2,0.00,NaN,NaN,NaN,NaN,B17.4,0.00,J70.6,0.00,G18.6,0.00,M41.9,0.00
836,612,13946241495,20240331,M,72,1,58493,21,1865,186.50,N,1865,0,3018.71,2469,186.50,0,H10.3,0,NaN,4466100399,6,3,697,91,10,0,NaN,N85.7,0.00,NaN,NaN,I10.4,0.00,P56.5,0.00,K43.5,0.00,L40.1,0.00,A85.1,0.00,NaN,NaN,P32.8,0.00,NaN,NaN,M10.3,0.00,H46.9,0.00
837,159,771527921896,20220819,M,72,1,60481,21,2184,218.40,A,2184,0,3788.06,3074,218.40,0,L46.3,0,NaN,826327102,5,0,863,12,10,0,NaN,B98.8,0.00,NaN,NaN,L67.8,0.00,NaN,NaN,M78.5,0.00,B61.4,0.00,D61.3,0.00,NaN,NaN,NaN,NaN,D10.1,0.00,J23.4,0.00,O64.2,0.00
838,893,983879068194,20220803,M,72,1,54369,3,2050,205.00,A,2050,0,4195.61,3050,205.00,0,C79.0,0,NaN,9080610616,1,4,602,78,10,0,NaN,B52.6,0.00,NaN,NaN,K72.1,0.00,NaN,NaN,NaN,NaN,NaN,NaN,A55.3,0.00,G41.1,0.00,F11.4,0.00,H42.5,0.00,O44.9,0.00,I43.0,0.00

From looking at some of the row names, we can see that their convention of naming is very short and non descriptive, making it difficult to figure out exactly what we are looking at. Fortunately, there are some row names that can be easily inferred, such as "CLAIMNO" and "CLM_TYP".

Another good chunck of info that can be inferred is the data types of the rows, as if we are going to begin analyzing them it is important that the values are of numerical origin. In other words, we cannot have a string variable or anything else aside from numerical values. Here we will be taking these types and converting them to floats, but first we have to see more on the data.

This is telling me the info of my dataFrame.

int vals = 1,2,3,4,5
text vals = alpha, beta, gamma, delta, epsilon
float values = 0.0, 0.25, 0.5, 0.75, 1

In [ ]:
df.info

<bound method DataFrame.info of      DSYSRTKY       CLAIMNO   THRU_DT RIC_CD  CLM_TYPE  DISP_CD  CARR_NUM  \
0         750  370940371571  20220224      M        72        1     80929
1         222  591576890071  20240618      M        72        1     18414
2         178  477751738951  20230527      M        72        1     25702
3         779  392843769636  20230204      M        72        1     55375
4         160  518369036545  20241123      M        72        1     83124
..        ...           ...       ...    ...       ...      ...       ...
834       753   74252124558  20221005      M        72        1     71337
835       130  598863377128  20231205      M        72        1     17240
836       612   13946241495  20240331      M        72        1     58493
837       159  771527921896  20220819      M        72        1     60481
838       893  983879068194  20220803      M        72        1     54369

    PMTDNLCD  PMT_AMT  PRPAYAMT ASGMNTCD  PROV_PMT  BENE_PMT  SBMTCHRG  \
0          2     2222    222.20        N      2222         0   3932.61
1          3     1314    131.40        N      1314         0   2621.24
2          4      848     84.80        N       848         0   1471.46
3         14     1365    136.50        N      1365         0   2178.37
4          B     2124    212.40        A      2124         0   3760.37
..       ...      ...       ...      ...       ...       ...       ...
834        0     1389    138.90        N      1389         0   2484.59
835        2      945     94.50        A       945         0   2131.61
836       21     1865    186.50        N      1865         0   3018.71
837       21     2184    218.40        A      2184         0   3788.06
838        3     2050    205.00        A      2050         0   4195.61

     ALOWCHRG  DEDAPPLY  HCPCS_YR PRNCPAL_DGNS_CD  PRNCPAL_DGNS_VRSN_CD  \
0        2925    222.20         0           G87.1                     0
1        2147    131.40         0           A80.5                     0
2        1248     84.80         0           L22.5                     0
3        1858    136.50         0           D76.0                     0
4        3212    212.40         0           N64.7                     0
..        ...       ...       ...             ...                   ...
834      1795    138.90         0           M66.6                     0
835      1514     94.50         0           H13.8                     0
836      2469    186.50         0           H10.3                     0
837      3074    218.40         0           L46.3                     0
838      3050    205.00         0           C79.0                     0

     RFR_UPIN     RFR_NPI  DOB_DT  RACE_CD  CNTY_CD  STATE_CD  \
0         NaN  7483169078       5        4      451        28
1         NaN  2625961895       6        3      970        70
2         NaN  7412281974       3        4      312        38
3         NaN  4476855727       2        0       18         1
4         NaN     3708693       5        3      154        53
..        ...         ...     ...      ...      ...       ...
834       NaN  8411378728       5        2      522        97
835       NaN  9063823528       4        3      477        84
836       NaN  4466100399       6        3      697        91
837       NaN   826327102       5        0      863        12
838       NaN  9080610616       1        4      602        78

     CWF_BENE_MDCR_STUS_CD  CLM_BENE_PD_AMT  ACO_ID_NUM ICD_DGNS_CD1  \
0                       10                0         NaN        A62.1
1                       10                0         NaN        A80.9
2                       10                0         NaN          NaN
3                       10                0         NaN        C57.2
4                       10                0         NaN          NaN
..                     ...              ...         ...          ...
834                     10                0         NaN        N55.5
835                     10                0         NaN          NaN
836                     10                0         NaN        N85.7
837                     10                0         NaN        B98.8
838                     10                0         NaN        B52.6

     ICD_DGNS_VRSN_CD1 ICD_DGNS_CD2  ICD_DGNS_VRSN_CD2 ICD_DGNS_CD3  \
0                 0.00          NaN                NaN        I14.2
1                 0.00          NaN                NaN        G77.3
2                  NaN          NaN                NaN        B35.6
3                 0.00        G49.6               0.00          NaN
4                  NaN        E66.3               0.00        J57.2
..                 ...          ...                ...          ...
834               0.00        P32.8               0.00        I41.2
835                NaN          NaN                NaN        K47.3
836               0.00          NaN                NaN        I10.4
837               0.00          NaN                NaN        L67.8
838               0.00          NaN                NaN        K72.1

     ICD_DGNS_VRSN_CD3 ICD_DGNS_CD4  ICD_DGNS_VRSN_CD4 ICD_DGNS_CD5  \
0                 0.00          NaN                NaN        P84.0
1                 0.00          NaN                NaN          NaN
2                 0.00        C81.5               0.00        A46.2
3                  NaN        N37.0               0.00          NaN
4                 0.00          NaN                NaN          NaN
..                 ...          ...                ...          ...
834               0.00          NaN                NaN          NaN
835               0.00          NaN                NaN          NaN
836               0.00        P56.5               0.00        K43.5
837               0.00          NaN                NaN        M78.5
838               0.00          NaN                NaN          NaN

     ICD_DGNS_VRSN_CD5 ICD_DGNS_CD6  ICD_DGNS_VRSN_CD6 ICD_DGNS_CD7  \
0                 0.00        B50.8               0.00        D42.7
1                  NaN        C28.7               0.00        A92.6
2                 0.00          NaN                NaN        K26.4
3                  NaN        E11.5               0.00        E71.3
4                  NaN          NaN                NaN          NaN
..                 ...          ...                ...          ...
834                NaN          NaN                NaN        J85.5
835                NaN        M99.2               0.00          NaN
836               0.00        L40.1               0.00        A85.1
837               0.00        B61.4               0.00        D61.3
838                NaN          NaN                NaN        A55.3

     ICD_DGNS_VRSN_CD7 ICD_DGNS_CD8  ICD_DGNS_VRSN_CD8 ICD_DGNS_CD9  \
0                 0.00        G65.1               0.00        K53.3
1                 0.00        E45.1               0.00          NaN
2                 0.00        H53.4               0.00        F54.3
3                 0.00        L81.0               0.00          NaN
4                  NaN          NaN                NaN        A27.9
..                 ...          ...                ...          ...
834               0.00        K29.5               0.00          NaN
835                NaN          NaN                NaN        B17.4
836               0.00          NaN                NaN        P32.8
837               0.00          NaN                NaN          NaN
838               0.00        G41.1               0.00        F11.4

     ICD_DGNS_VRSN_CD9 ICD_DGNS_CD10  ICD_DGNS_VRSN_CD10 ICD_DGNS_CD11  \
0                 0.00           NaN                 NaN         J81.3
1                  NaN         A62.7                0.00           NaN
2                 0.00         I86.5                0.00           NaN
3                  NaN         N62.8                0.00           NaN
4                 0.00         B76.9                0.00           NaN
..                 ...           ...                 ...           ...
834                NaN         N54.0                0.00           NaN
835               0.00         J70.6                0.00         G18.6
836               0.00           NaN                 NaN         M10.3
837                NaN         D10.1                0.00         J23.4
838               0.00         H42.5                0.00         O44.9

     ICD_DGNS_VRSN_CD11 ICD_DGNS_CD12  ICD_DGNS_VRSN_CD12
0                  0.00         D14.0                0.00
1                   NaN         C75.8                0.00
2                   NaN         P70.8                0.00
3                   NaN           NaN                 NaN
4                   NaN           NaN                 NaN
..                  ...           ...                 ...
834                 NaN           NaN                 NaN
835                0.00         M41.9                0.00
836                0.00         H46.9                0.00
837                0.00         O64.2                0.00
838                0.00         I43.0                0.00

[839 rows x 52 columns]>

In [ ]:
df.dtypes

DSYSRTKY                   int64
CLAIMNO                    int64
THRU_DT                    int64
RIC_CD                    object
CLM_TYPE                   int64
DISP_CD                    int64
CARR_NUM                   int64
PMTDNLCD                  object
PMT_AMT                    int64
PRPAYAMT                 float64
ASGMNTCD                  object
PROV_PMT                   int64
BENE_PMT                   int64
SBMTCHRG                 float64
ALOWCHRG                   int64
DEDAPPLY                 float64
HCPCS_YR                   int64
PRNCPAL_DGNS_CD           object
PRNCPAL_DGNS_VRSN_CD       int64
RFR_UPIN                 float64
RFR_NPI                    int64
DOB_DT                     int64
RACE_CD                    int64
CNTY_CD                    int64
STATE_CD                   int64
CWF_BENE_MDCR_STUS_CD      int64
CLM_BENE_PD_AMT            int64
ACO_ID_NUM               float64
ICD_DGNS_CD1              object
ICD_DGNS_VRSN_CD1        float64
ICD_DGNS_CD2              object
ICD_DGNS_VRSN_CD2        float64
ICD_DGNS_CD3              object
ICD_DGNS_VRSN_CD3        float64
ICD_DGNS_CD4              object
ICD_DGNS_VRSN_CD4        float64
ICD_DGNS_CD5              object
ICD_DGNS_VRSN_CD5        float64
ICD_DGNS_CD6              object
ICD_DGNS_VRSN_CD6        float64
ICD_DGNS_CD7              object
ICD_DGNS_VRSN_CD7        float64
ICD_DGNS_CD8              object
ICD_DGNS_VRSN_CD8        float64
ICD_DGNS_CD9              object
ICD_DGNS_VRSN_CD9        float64
ICD_DGNS_CD10             object
ICD_DGNS_VRSN_CD10       float64
ICD_DGNS_CD11             object
ICD_DGNS_VRSN_CD11       float64
ICD_DGNS_CD12             object
ICD_DGNS_VRSN_CD12       float64
dtype: object

In [ ]:
df.describe()

,DSYSRTKY,CLAIMNO,THRU_DT,CLM_TYPE,DISP_CD,CARR_NUM,PMT_AMT,PRPAYAMT,PROV_PMT,BENE_PMT,SBMTCHRG,ALOWCHRG,DEDAPPLY,HCPCS_YR,PRNCPAL_DGNS_VRSN_CD,RFR_UPIN,RFR_NPI,DOB_DT,RACE_CD,CNTY_CD,STATE_CD,CWF_BENE_MDCR_STUS_CD,CLM_BENE_PD_AMT,ACO_ID_NUM,ICD_DGNS_VRSN_CD1,ICD_DGNS_VRSN_CD2,ICD_DGNS_VRSN_CD3,ICD_DGNS_VRSN_CD4,ICD_DGNS_VRSN_CD5,ICD_DGNS_VRSN_CD6,ICD_DGNS_VRSN_CD7,ICD_DGNS_VRSN_CD8,ICD_DGNS_VRSN_CD9,ICD_DGNS_VRSN_CD10,ICD_DGNS_VRSN_CD11,ICD_DGNS_VRSN_CD12
count,839.00,839.00,839.00,839.00,839.00,839.00,839.00,839.00,839.00,839.00,839.00,839.00,839.00,839.00,839.00,0.00,839.00,839.00,839.00,839.00,839.00,839.00,839.00,0.00,480.00,487.00,504.00,486.00,491.00,495.00,501.00,495.00,500.00,515.00,486.00,506.00
mean,498.13,492782137216.33,20230585.36,72.00,1.00,50092.85,1798.48,179.85,1798.48,0.00,3235.60,2583.51,179.85,0.00,0.00,NaN,4957000518.66,3.50,3.07,477.54,50.69,10.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
std,289.16,283271582880.57,8048.80,0.00,0.00,29562.84,2020.29,202.03,2020.29,0.00,3654.18,2898.83,202.03,0.00,0.00,NaN,2948716670.42,1.75,1.99,284.10,29.70,0.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
min,1.00,842757415.00,20220101.00,72.00,1.00,135.00,50.00,5.00,50.00,0.00,102.68,75.00,5.00,0.00,0.00,NaN,3708693.00,1.00,0.00,2.00,0.00,10.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,232.50,255994647365.50,20221002.50,72.00,1.00,24321.50,733.50,73.35,733.50,0.00,1304.32,1025.50,73.35,0.00,0.00,NaN,2496630325.00,2.00,1.00,221.00,24.00,10.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,503.00,489416455876.00,20230626.00,72.00,1.00,50176.00,1398.00,139.80,1398.00,0.00,2549.68,2045.00,139.80,0.00,0.00,NaN,4717710069.00,4.00,3.00,477.00,50.00,10.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,757.00,729679764641.50,20240315.00,72.00,1.00,75083.50,2205.00,220.50,2205.00,0.00,3982.91,3159.50,220.50,0.00,0.00,NaN,7796064608.00,5.00,5.00,717.00,77.50,10.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,999.00,999719851899.00,20241227.00,72.00,1.00,99930.00,18693.00,1869.30,18693.00,0.00,29887.09,24320.00,1869.30,0.00,0.00,NaN,9932114863.00,6.00,6.00,996.00,99.00,10.00,0.00,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

Now we are going to check for duplicates and missing values throughout the dataFrame and handle them accordingly. We will be using " df.isnull().sum() " to check missing values, as returning anything other than a zero would indicate there are indeed missing values. We will also be using " df.duplicated().sum() " to check for any duplicate values.

In [ ]:
df.isnull().sum()

df.duplicated().sum()

np.int64(0)

We can see by pulling the data type of all the values from the DMERC that the type values range from object, int, and floats. What we will be looking at specifically is the object type values and our goal is to convert those values into float type variables.

To do this, we will utilize a panda function that

In [ ]:
objec_colm = df.select_dtypes(include='object').columns
print(objec_colm)
int_colm = df.select_dtypes(include='int64').columns
print(int_colm)

Index(['RIC_CD', 'PMTDNLCD', 'ASGMNTCD', 'PRNCPAL_DGNS_CD', 'ICD_DGNS_CD1',
       'ICD_DGNS_CD2', 'ICD_DGNS_CD3', 'ICD_DGNS_CD4', 'ICD_DGNS_CD5',
       'ICD_DGNS_CD6', 'ICD_DGNS_CD7', 'ICD_DGNS_CD8', 'ICD_DGNS_CD9',
       'ICD_DGNS_CD10', 'ICD_DGNS_CD11', 'ICD_DGNS_CD12'],
      dtype='object')
Index(['DSYSRTKY', 'CLAIMNO', 'THRU_DT', 'CLM_TYPE', 'DISP_CD', 'CARR_NUM',
       'PMT_AMT', 'PROV_PMT', 'BENE_PMT', 'ALOWCHRG', 'HCPCS_YR',
       'PRNCPAL_DGNS_VRSN_CD', 'RFR_NPI', 'DOB_DT', 'RACE_CD', 'CNTY_CD',
       'STATE_CD', 'CWF_BENE_MDCR_STUS_CD', 'CLM_BENE_PD_AMT'],
      dtype='object')

In [ ]:
for col in objec_colm:
 df[col] = df[col].astype(str).str.replace(',', '').str.strip()
 df[col] = pd.to_numeric(df[col], errors='coerce')

for col in int_colm:
 df[col] = df[col].astype(str)

In [ ]:
df.dtypes

DSYSRTKY                  object
CLAIMNO                   object
THRU_DT                   object
RIC_CD                   float64
CLM_TYPE                  object
DISP_CD                   object
CARR_NUM                  object
PMTDNLCD                 float64
PMT_AMT                   object
PRPAYAMT                 float64
ASGMNTCD                 float64
PROV_PMT                  object
BENE_PMT                  object
SBMTCHRG                 float64
ALOWCHRG                  object
DEDAPPLY                 float64
HCPCS_YR                  object
PRNCPAL_DGNS_CD          float64
PRNCPAL_DGNS_VRSN_CD      object
RFR_UPIN                 float64
RFR_NPI                   object
DOB_DT                    object
RACE_CD                   object
CNTY_CD                   object
STATE_CD                  object
CWF_BENE_MDCR_STUS_CD     object
CLM_BENE_PD_AMT           object
ACO_ID_NUM               float64
ICD_DGNS_CD1             float64
ICD_DGNS_VRSN_CD1        float64
ICD_DGNS_CD2             float64
ICD_DGNS_VRSN_CD2        float64
ICD_DGNS_CD3             float64
ICD_DGNS_VRSN_CD3        float64
ICD_DGNS_CD4             float64
ICD_DGNS_VRSN_CD4        float64
ICD_DGNS_CD5             float64
ICD_DGNS_VRSN_CD5        float64
ICD_DGNS_CD6             float64
ICD_DGNS_VRSN_CD6        float64
ICD_DGNS_CD7             float64
ICD_DGNS_VRSN_CD7        float64
ICD_DGNS_CD8             float64
ICD_DGNS_VRSN_CD8        float64
ICD_DGNS_CD9             float64
ICD_DGNS_VRSN_CD9        float64
ICD_DGNS_CD10            float64
ICD_DGNS_VRSN_CD10       float64
ICD_DGNS_CD11            float64
ICD_DGNS_VRSN_CD11       float64
ICD_DGNS_CD12            float64
ICD_DGNS_VRSN_CD12       float64
dtype: object

In [ ]:
df.tail()

,DSYSRTKY,CLAIMNO,THRU_DT,RIC_CD,CLM_TYPE,DISP_CD,CARR_NUM,PMTDNLCD,PMT_AMT,PRPAYAMT,...,ICD_DGNS_CD8,ICD_DGNS_VRSN_CD8,ICD_DGNS_CD9,ICD_DGNS_VRSN_CD9,ICD_DGNS_CD10,ICD_DGNS_VRSN_CD10,ICD_DGNS_CD11,ICD_DGNS_VRSN_CD11,ICD_DGNS_CD12,ICD_DGNS_VRSN_CD12
834,753,74252124558,20221005,NaN,72,1,71337,0.0,1389,138.9,...,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
835,130,598863377128,20231205,NaN,72,1,17240,2.0,945,94.5,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0
836,612,13946241495,20240331,NaN,72,1,58493,21.0,1865,186.5,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,0.0
837,159,771527921896,20220819,NaN,72,1,60481,21.0,2184,218.4,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0
838,893,983879068194,20220803,NaN,72,1,54369,3.0,2050,205.0,...,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0

In [ ]:
from google.colab import files

df.to_csv('modified_dmerc_data.csv', index=False)
files.download('modified_dmerc_data.csv')