<a href="https://colab.research.google.com/github/thcen-dev/ai-health-data-project/blob/midHeap/Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 01

First we are going to upload the dmerc csv file as type "df" and will then display all the names of the rows within the csv.

In [4]:
import pandas as pd

# Replace 'your_file_path.csv' with the actual path to your CSV file
df = pd.read_csv('/content/synthetic_dmerc_base (1).csv')

To get a general feel for what the nature of the data is, we will first look at the first five rows of the data set using "df.head()" and will also look at the bottom five, or "df.tail" of the dataset to ensure accuracy in what we are understanding. We are already given the name of the csv which contains"dmerc", which stands for Durable Medical Equipment, but it is safe practice to ensure data accuracy.

In [6]:
#pulls the first five rows of the dataset
df.head()

,DSYSRTKY,CLAIMNO,THRU_DT,RIC_CD,CLM_TYPE,DISP_CD,CARR_NUM,PMTDNLCD,PMT_AMT,PRPAYAMT,...,ICD_DGNS_CD8,ICD_DGNS_VRSN_CD8,ICD_DGNS_CD9,ICD_DGNS_VRSN_CD9,ICD_DGNS_CD10,ICD_DGNS_VRSN_CD10,ICD_DGNS_CD11,ICD_DGNS_VRSN_CD11,ICD_DGNS_CD12,ICD_DGNS_VRSN_CD12
0,750,370940371571,20220224,M,72,1,80929,2,2222,222.2,...,G65.1,0.0,K53.3,0.0,NaN,NaN,J81.3,0.0,D14.0,0.0
1,222,591576890071,20240618,M,72,1,18414,3,1314,131.4,...,E45.1,0.0,NaN,NaN,A62.7,0.0,NaN,NaN,C75.8,0.0
2,178,477751738951,20230527,M,72,1,25702,4,848,84.8,...,H53.4,0.0,F54.3,0.0,I86.5,0.0,NaN,NaN,P70.8,0.0
3,779,392843769636,20230204,M,72,1,55375,14,1365,136.5,...,L81.0,0.0,NaN,NaN,N62.8,0.0,NaN,NaN,NaN,NaN
4,160,518369036545,20241123,M,72,1,83124,B,2124,212.4,...,NaN,NaN,A27.9,0.0,B76.9,0.0,NaN,NaN,NaN,NaN

In [7]:
#pulls the last five rows of the dataset
df.tail()

,DSYSRTKY,CLAIMNO,THRU_DT,RIC_CD,CLM_TYPE,DISP_CD,CARR_NUM,PMTDNLCD,PMT_AMT,PRPAYAMT,...,ICD_DGNS_CD8,ICD_DGNS_VRSN_CD8,ICD_DGNS_CD9,ICD_DGNS_VRSN_CD9,ICD_DGNS_CD10,ICD_DGNS_VRSN_CD10,ICD_DGNS_CD11,ICD_DGNS_VRSN_CD11,ICD_DGNS_CD12,ICD_DGNS_VRSN_CD12
834,753,74252124558,20221005,M,72,1,71337,0,1389,138.9,...,K29.5,0.0,NaN,NaN,N54.0,0.0,NaN,NaN,NaN,NaN
835,130,598863377128,20231205,M,72,1,17240,2,945,94.5,...,NaN,NaN,B17.4,0.0,J70.6,0.0,G18.6,0.0,M41.9,0.0
836,612,13946241495,20240331,M,72,1,58493,21,1865,186.5,...,NaN,NaN,P32.8,0.0,NaN,NaN,M10.3,0.0,H46.9,0.0
837,159,771527921896,20220819,M,72,1,60481,21,2184,218.4,...,NaN,NaN,NaN,NaN,D10.1,0.0,J23.4,0.0,O64.2,0.0
838,893,983879068194,20220803,M,72,1,54369,3,2050,205.0,...,G41.1,0.0,F11.4,0.0,H42.5,0.0,O44.9,0.0,I43.0,0.0

From looking at some of the row names, we can see that their convention of naming is very short and non descriptive, making it difficult to figure out exactly what we are looking at. Fortunately, there are some row names that can be easily inferred, such as "CLAIMNO" and "CLM_TYP".

Another good chunck of info that can be inferred is the data types of the rows, as if we are going to begin analyzing them it is important that the values are of numerical origin. In other words, we cannot have a string variable or anything else aside from numerical values. Here we will be taking these types and converting them to floats, but first we have to see more on the data.