<a href="https://colab.research.google.com/github/thcen-dev/ai-health-data-project/blob/midHeap/Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment 01

First we are going to upload the dmerc csv file as type "df" and will then display all the names of the rows within the csv.

In [1]:
import pandas as pd

# Replace 'your_file_path.csv' with the actual path to your CSV file
df = pd.read_csv('/content/synthetic_dmerc_base (1).csv')

To get a general feel for what the nature of the data is, we will first look at the first five rows of the data set using "df.head()" and will also look at the bottom five, or "df.tail" of the dataset to ensure accuracy in what we are understanding. We are already given the name of the csv which contains"dmerc", which stands for Durable Medical Equipment, but it is safe practice to ensure data accuracy.

In [2]:
#pulls the first five rows of the dataset
df.head()

,DSYSRTKY,CLAIMNO,THRU_DT,RIC_CD,CLM_TYPE,DISP_CD,CARR_NUM,PMTDNLCD,PMT_AMT,PRPAYAMT,...,ICD_DGNS_CD8,ICD_DGNS_VRSN_CD8,ICD_DGNS_CD9,ICD_DGNS_VRSN_CD9,ICD_DGNS_CD10,ICD_DGNS_VRSN_CD10,ICD_DGNS_CD11,ICD_DGNS_VRSN_CD11,ICD_DGNS_CD12,ICD_DGNS_VRSN_CD12
0,750,370940371571,20220224,M,72,1,80929,2,2222,222.2,...,G65.1,0.0,K53.3,0.0,NaN,NaN,J81.3,0.0,D14.0,0.0
1,222,591576890071,20240618,M,72,1,18414,3,1314,131.4,...,E45.1,0.0,NaN,NaN,A62.7,0.0,NaN,NaN,C75.8,0.0
2,178,477751738951,20230527,M,72,1,25702,4,848,84.8,...,H53.4,0.0,F54.3,0.0,I86.5,0.0,NaN,NaN,P70.8,0.0
3,779,392843769636,20230204,M,72,1,55375,14,1365,136.5,...,L81.0,0.0,NaN,NaN,N62.8,0.0,NaN,NaN,NaN,NaN
4,160,518369036545,20241123,M,72,1,83124,B,2124,212.4,...,NaN,NaN,A27.9,0.0,B76.9,0.0,NaN,NaN,NaN,NaN

In [3]:
#pulls the last five rows of the dataset
df.tail()

,DSYSRTKY,CLAIMNO,THRU_DT,RIC_CD,CLM_TYPE,DISP_CD,CARR_NUM,PMTDNLCD,PMT_AMT,PRPAYAMT,...,ICD_DGNS_CD8,ICD_DGNS_VRSN_CD8,ICD_DGNS_CD9,ICD_DGNS_VRSN_CD9,ICD_DGNS_CD10,ICD_DGNS_VRSN_CD10,ICD_DGNS_CD11,ICD_DGNS_VRSN_CD11,ICD_DGNS_CD12,ICD_DGNS_VRSN_CD12
834,753,74252124558,20221005,M,72,1,71337,0,1389,138.9,...,K29.5,0.0,NaN,NaN,N54.0,0.0,NaN,NaN,NaN,NaN
835,130,598863377128,20231205,M,72,1,17240,2,945,94.5,...,NaN,NaN,B17.4,0.0,J70.6,0.0,G18.6,0.0,M41.9,0.0
836,612,13946241495,20240331,M,72,1,58493,21,1865,186.5,...,NaN,NaN,P32.8,0.0,NaN,NaN,M10.3,0.0,H46.9,0.0
837,159,771527921896,20220819,M,72,1,60481,21,2184,218.4,...,NaN,NaN,NaN,NaN,D10.1,0.0,J23.4,0.0,O64.2,0.0
838,893,983879068194,20220803,M,72,1,54369,3,2050,205.0,...,G41.1,0.0,F11.4,0.0,H42.5,0.0,O44.9,0.0,I43.0,0.0

From looking at some of the row names, we can see that their convention of naming is very short and non descriptive, making it difficult to figure out exactly what we are looking at. Fortunately, there are some row names that can be easily inferred, such as "CLAIMNO" and "CLM_TYP".

Another good chunck of info that can be inferred is the data types of the rows, as if we are going to begin analyzing them it is important that the values are of numerical origin. In other words, we cannot have a string variable or anything else aside from numerical values. Here we will be taking these types and converting them to floats, but first we have to see more on the data.

In [4]:
df.dtypes

DSYSRTKY                   int64
CLAIMNO                    int64
THRU_DT                    int64
RIC_CD                    object
CLM_TYPE                   int64
DISP_CD                    int64
CARR_NUM                   int64
PMTDNLCD                  object
PMT_AMT                    int64
PRPAYAMT                 float64
ASGMNTCD                  object
PROV_PMT                   int64
BENE_PMT                   int64
SBMTCHRG                 float64
ALOWCHRG                   int64
DEDAPPLY                 float64
HCPCS_YR                   int64
PRNCPAL_DGNS_CD           object
PRNCPAL_DGNS_VRSN_CD       int64
RFR_UPIN                 float64
RFR_NPI                    int64
DOB_DT                     int64
RACE_CD                    int64
CNTY_CD                    int64
STATE_CD                   int64
CWF_BENE_MDCR_STUS_CD      int64
CLM_BENE_PD_AMT            int64
ACO_ID_NUM               float64
ICD_DGNS_CD1              object
ICD_DGNS_VRSN_CD1        float64
ICD_DGNS_CD2              object
ICD_DGNS_VRSN_CD2        float64
ICD_DGNS_CD3              object
ICD_DGNS_VRSN_CD3        float64
ICD_DGNS_CD4              object
ICD_DGNS_VRSN_CD4        float64
ICD_DGNS_CD5              object
ICD_DGNS_VRSN_CD5        float64
ICD_DGNS_CD6              object
ICD_DGNS_VRSN_CD6        float64
ICD_DGNS_CD7              object
ICD_DGNS_VRSN_CD7        float64
ICD_DGNS_CD8              object
ICD_DGNS_VRSN_CD8        float64
ICD_DGNS_CD9              object
ICD_DGNS_VRSN_CD9        float64
ICD_DGNS_CD10             object
ICD_DGNS_VRSN_CD10       float64
ICD_DGNS_CD11             object
ICD_DGNS_VRSN_CD11       float64
ICD_DGNS_CD12             object
ICD_DGNS_VRSN_CD12       float64
dtype: object

In [5]:
df.describe()

,DSYSRTKY,CLAIMNO,THRU_DT,CLM_TYPE,DISP_CD,CARR_NUM,PMT_AMT,PRPAYAMT,PROV_PMT,BENE_PMT,...,ICD_DGNS_VRSN_CD3,ICD_DGNS_VRSN_CD4,ICD_DGNS_VRSN_CD5,ICD_DGNS_VRSN_CD6,ICD_DGNS_VRSN_CD7,ICD_DGNS_VRSN_CD8,ICD_DGNS_VRSN_CD9,ICD_DGNS_VRSN_CD10,ICD_DGNS_VRSN_CD11,ICD_DGNS_VRSN_CD12
count,839.000000,8.390000e+02,8.390000e+02,839.0,839.0,839.000000,839.000000,839.000000,839.000000,839.0,...,504.0,486.0,491.0,495.0,501.0,495.0,500.0,515.0,486.0,506.0
mean,498.133492,4.927821e+11,2.023059e+07,72.0,1.0,50092.852205,1798.480334,179.848033,1798.480334,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,289.164340,2.832716e+11,8.048795e+03,0.0,0.0,29562.838828,2020.290939,202.029094,2020.290939,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,1.000000,8.427574e+08,2.022010e+07,72.0,1.0,135.000000,50.000000,5.000000,50.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,232.500000,2.559946e+11,2.022100e+07,72.0,1.0,24321.500000,733.500000,73.350000,733.500000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,503.000000,4.894165e+11,2.023063e+07,72.0,1.0,50176.000000,1398.000000,139.800000,1398.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,757.000000,7.296798e+11,2.024032e+07,72.0,1.0,75083.500000,2205.000000,220.500000,2205.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,999.000000,9.997199e+11,2.024123e+07,72.0,1.0,99930.000000,18693.000000,1869.300000,18693.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

We can see by pulling the data type of all the values from the DMERC that the type values range from object, int, and floats. What we will be looking at specifically is the object type values and our goal is to convert those values into float type variables.

To do this, we will utilize a panda function that

In [ ]:
objec_colm = df.select_dtypes(include='object').columns
print(objec_colm)
int_colm = df.select_dtypes(include='int64').columns
print(int_colm)

Index(['RIC_CD', 'PMTDNLCD', 'ASGMNTCD', 'PRNCPAL_DGNS_CD', 'ICD_DGNS_CD1',
       'ICD_DGNS_CD2', 'ICD_DGNS_CD3', 'ICD_DGNS_CD4', 'ICD_DGNS_CD5',
       'ICD_DGNS_CD6', 'ICD_DGNS_CD7', 'ICD_DGNS_CD8', 'ICD_DGNS_CD9',
       'ICD_DGNS_CD10', 'ICD_DGNS_CD11', 'ICD_DGNS_CD12'],
      dtype='object')
Index(['DSYSRTKY', 'CLAIMNO', 'THRU_DT', 'CLM_TYPE', 'DISP_CD', 'CARR_NUM',
       'PMT_AMT', 'PROV_PMT', 'BENE_PMT', 'ALOWCHRG', 'HCPCS_YR',
       'PRNCPAL_DGNS_VRSN_CD', 'RFR_NPI', 'DOB_DT', 'RACE_CD', 'CNTY_CD',
       'STATE_CD', 'CWF_BENE_MDCR_STUS_CD', 'CLM_BENE_PD_AMT'],
      dtype='object')

In [ ]:
for col in objec_colm:
 df[col] = df[col].astype(str).str.replace(',', '').str.strip()
 df[col] = pd.to_numeric(df[col], errors='coerce')

for col in int_colm:
 df[col] = df[col].astype(str)

In [ ]:
df.dtypes

DSYSRTKY                  object
CLAIMNO                   object
THRU_DT                   object
RIC_CD                   float64
CLM_TYPE                  object
DISP_CD                   object
CARR_NUM                  object
PMTDNLCD                 float64
PMT_AMT                   object
PRPAYAMT                 float64
ASGMNTCD                 float64
PROV_PMT                  object
BENE_PMT                  object
SBMTCHRG                 float64
ALOWCHRG                  object
DEDAPPLY                 float64
HCPCS_YR                  object
PRNCPAL_DGNS_CD          float64
PRNCPAL_DGNS_VRSN_CD      object
RFR_UPIN                 float64
RFR_NPI                   object
DOB_DT                    object
RACE_CD                   object
CNTY_CD                   object
STATE_CD                  object
CWF_BENE_MDCR_STUS_CD     object
CLM_BENE_PD_AMT           object
ACO_ID_NUM               float64
ICD_DGNS_CD1             float64
ICD_DGNS_VRSN_CD1        float64
ICD_DGNS_CD2             float64
ICD_DGNS_VRSN_CD2        float64
ICD_DGNS_CD3             float64
ICD_DGNS_VRSN_CD3        float64
ICD_DGNS_CD4             float64
ICD_DGNS_VRSN_CD4        float64
ICD_DGNS_CD5             float64
ICD_DGNS_VRSN_CD5        float64
ICD_DGNS_CD6             float64
ICD_DGNS_VRSN_CD6        float64
ICD_DGNS_CD7             float64
ICD_DGNS_VRSN_CD7        float64
ICD_DGNS_CD8             float64
ICD_DGNS_VRSN_CD8        float64
ICD_DGNS_CD9             float64
ICD_DGNS_VRSN_CD9        float64
ICD_DGNS_CD10            float64
ICD_DGNS_VRSN_CD10       float64
ICD_DGNS_CD11            float64
ICD_DGNS_VRSN_CD11       float64
ICD_DGNS_CD12            float64
ICD_DGNS_VRSN_CD12       float64
dtype: object

In [ ]:
df.tail()

,DSYSRTKY,CLAIMNO,THRU_DT,RIC_CD,CLM_TYPE,DISP_CD,CARR_NUM,PMTDNLCD,PMT_AMT,PRPAYAMT,...,ICD_DGNS_CD8,ICD_DGNS_VRSN_CD8,ICD_DGNS_CD9,ICD_DGNS_VRSN_CD9,ICD_DGNS_CD10,ICD_DGNS_VRSN_CD10,ICD_DGNS_CD11,ICD_DGNS_VRSN_CD11,ICD_DGNS_CD12,ICD_DGNS_VRSN_CD12
834,753,74252124558,20221005,NaN,72,1,71337,0.0,1389,138.9,...,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
835,130,598863377128,20231205,NaN,72,1,17240,2.0,945,94.5,...,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0
836,612,13946241495,20240331,NaN,72,1,58493,21.0,1865,186.5,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,0.0
837,159,771527921896,20220819,NaN,72,1,60481,21.0,2184,218.4,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0
838,893,983879068194,20220803,NaN,72,1,54369,3.0,2050,205.0,...,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0

In [ ]:
from google.colab import files

df.to_csv('modified_dmerc_data.csv', index=False)
files.download('modified_dmerc_data.csv')